kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: v31
nodes:
  - role: control-plane
    image: kindest/node:v1.31.6
    extraMounts:
      - hostPath: ./kube-prometheus-stack/data/prometheus
        containerPath: /data/prometheus
      - hostPath: ./kube-prometheus-stack/data/grafana
        containerPath: /var/lib/grafana
    kubeadmConfigPatches:
      - |-
        kind: ClusterConfiguration
        controllerManager:
          extraArgs:
            kube-api-qps: "2000" # <--QPS
            kube-api-burst: "2000" # <--QPS
            node-monitor-grace-period: "7200s"
            node-monitor-period: "3600s"
            concurrent-job-syncs: "100"
        etcd:
          local:
            extraArgs:
              quota-backend-bytes: "8589934592"
              auto-compaction-mode: revision
              auto-compaction-retention: "2000"
        scheduler:
          extraArgs:
            kube-api-qps: "2000" # <--QPS
            kube-api-burst: "2000" # <--QPS
        apiServer:
          extraArgs:
            max-mutating-requests-inflight: "20000"
            max-requests-inflight: "20000"
  - role: worker
    image: kindest/node:v1.31.6
    kubeadmConfigPatches:
      - |-
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            register-with-taints: "spark-operator=true:NoSchedule"
  - role: worker
    image: kindest/node:v1.31.6
    extraMounts:
      - hostPath: ./kube-prometheus-stack/data/prometheus
        containerPath: /data/prometheus
      - hostPath: ./kube-prometheus-stack/data/grafana
        containerPath: /var/lib/grafana
      - hostPath: ../tpc/nds/results
        containerPath: /mnt/benchmark-results
