prometheus:
  prometheusSpec:
    retention: 90d
    retentionSize: 18Gi
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-data
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
