apiVersion: v1
kind: ConfigMap
metadata:
  name: kwok
  namespace: kube-system
data:
  kwok.yaml: |
    apiVersion: config.kwok.x-k8s.io/v1alpha1
    kind: KwokConfiguration
    options:
      nodeLeaseParallelism: 32
      podPlayStageParallelism: 32
      nodePlayStageParallelism: 32
      nodeLeaseDurationSeconds: 3600
      
      enableProfilingHandler: false
      enableContentionProfiling: false
      enablePodsOnNodeSyncListPager: false
      enablePodsOnNodeSyncStreamWatch: true
      nodePort: 10247
      cidr: 10.0.0.1/24
      manageAllNodes: false
      manageNodesWithAnnotationSelector: 'kwok.x-k8s.io/node=fake'
      manageNodesWithLabelSelector: ''
      manageSingleNode: ''
      enableCRDs:
        - Stage
        - Metric
        - Attach
        - ClusterAttach
        - Exec
        - ClusterExec
        - Logs
        - ClusterLogs
        - PortForward
        - ClusterPortForward
        - ResourceUsage
        - ClusterResourceUsage
