#global:
#gc: true
#measurements:
#  - name: podLatency
#  - name: jobLatency
#  - name: pvcLatency

#metricsEndpoints:
#  - indexer:
#      type: local

jobs:
  - name: jobs-throughput
    namespace: spark-jobs
    jobIterations: 1
    qps: 100
    burst: 100
    waitWhenFinished: true
    objects:
      - objectTemplate: apache.job.yaml.tmpl
        replicas: 8000
        waitOptions:
          customStatusPaths:
            - key: ".currentState.currentStateSummary"
              value: "TerminatedWithoutReleaseResources"
