apiVersion: spark.apache.org/v1alpha1
kind: SparkApplication
metadata:
  name: "job-{{ .Index }}"
  namespace: "apache-jobs"
spec:
  mainClass: "org.apache.spark.examples.SparkPi"
  jars: "local:///opt/spark/examples/jars/spark-examples.jar"
  sparkConf:
    spark.kubernetes.authenticate.driver.serviceAccountName: "spark"
    spark.kubernetes.container.image: "apache/spark:4.0.0-preview2"
    spark.executor.instances: "1"
    spark.driver.cores: "1"
    spark.driver.memory: "512m"

    spark.kubernetes.scheduler: "yunikorn"
  applicationTolerations:
    resourceRetainPolicy: Always
  runtimeVersions:
    scalaVersion: "2.13"
    sparkVersion: "4.0.0-preview2"

  driverSpec:
    podTemplateSpec:
      metadata:
        labels:
          "pod-complete.stage.kwok.x-k8s.io/completed": "true"
      spec:
        nodeSelector:
          type: "kwok"
        tolerations:
          - effect: "NoSchedule"
            key: "kwok.x-k8s.io/node"
            operator: "Exists"
